fileops.py: Fix a traceback clearing teh old profile link
The isdir() cconditional was not enough, it also needed to make sure it was not a symlink.

25 Jun 2016 08:02:45 PDT: NOTICE  : --- Running action sequence: config_profile_link
25 Jun 2016 08:02:45 PDT: ERROR   : clear_dir failed
Traceback (most recent call last):
  File "/home/brian/Dev/git/catalyst/catalyst/fileops.py", line 84, in clear_dir
    shutil.rmtree(target)
  File "/usr/lib64/python3.4/shutil.py", line 478, in rmtree
    onerror(os.path.islink, path, sys.exc_info())
  File "/usr/lib64/python3.4/shutil.py", line 476, in rmtree
    raise OSError("Cannot call rmtree on a symbolic link")
OSError: Cannot call rmtree on a symbolic link