Revert "catalyst/main.py: Fix variables not being substituted with correct values"
This reverts commit 4328dcd693ae02a77c519e5186e5430171c16ac5.

Reverting due to :

Envscript support enabled.
Traceback (most recent call last):
  File "/usr/lib/python-exec/python2.7/catalyst", line 39, in <module>
    main()
  File "/usr/lib64/python2.7/site-packages/catalyst/main.py", line 343, in main
    build_target(addlargs)
  File "/usr/lib64/python2.7/site-packages/catalyst/main.py", line 158, in build_target
    target = getattr(module, target)(conf_values, addlargs)
  File "/usr/lib64/python2.7/site-packages/catalyst/targets/stage1.py", line 21, in __init__
    StageBase.__init__(self,spec,addlargs)
  File "/usr/lib64/python2.7/site-packages/catalyst/base/stagebase.py", line 72, in __init__
    for x in [x[:-3] for x in os.listdir(arch_dir) if x.endswith(".py") and x != "__init__.py"]:
OSError: [Errno 2] No such file or directory: './catalyst/arch/'